# This is a basic workflow to help you get started with Actions

name: Error Handling Demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu_latest
    steps:
    - name: checkout the branch
      uses: actions/checkout@v4
    - name: Step that fails, but workflow continues
      run: exit 1
        continue-on-error: true
    - name: Run if the previous step failed
      if: failure()
      run: echo "Previous step failed, handled gracefully."
    - name: Run if the previous step succeeded
      if: success()
      run: echo "Previous step succeeded.",
    - name: Always run this step
      if: always()
      run: echo "This runs no matter what."
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deployment step
        run: echo "Deploying the application..."
